# Generated by Django 5.1.2 on 2025-06-16 03:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='是否冻结'),
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('FREEZE', '冻结账号'), ('UNFREEZE', '解冻账号')], max_length=10, verbose_name='操作类型')),
                ('reason', models.TextField(blank=True, verbose_name='操作原因')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '管理员操作记录',
                'verbose_name_plural': '管理员操作记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
