# Generated by Django 5.1.2 on 2025-05-30 18:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='plain_content',
            field=models.TextField(blank=True, null=True, verbose_name='纯文本内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
    ]
