# Generated by Django 5.1.2 on 2025-06-01 07:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_sharearticle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='deletion_reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='删除原因'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_deleted'], name='article_art_is_dele_6452c1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['deleted_at'], name='article_art_deleted_c9e4df_idx'),
        ),
    ]
