# Generated by Django 5.1.2 on 2025-06-16 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options_article_deletion_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章管理'},
        ),
    ]
