# Generated by Django 5.1.2 on 2025-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharearticle',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='已下架'),
        ),
    ]
