# Generated by Django 5.1.2 on 2025-06-18 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_sharearticle_is_removed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('share_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.sharearticle', verbose_name='分享文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
