# Generated by Django 5.1.2 on 2025-06-19 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_category_article_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mptt_level',
            new_name='level',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'parent', 'author')},
        ),
    ]
