# Generated by Django 5.1.2 on 2025-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_rename_mptt_level_category_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name='文章图片'),
        ),
    ]
